language: ruby
before_install:
  - gem install bundler
install: bundle install --jobs=1 --retry=1
script:
  - bundle install
  - bundle exec rspec

rvm:
matrix:
  include:
    # We'll have to back up to grape-swagger 0.11 for earlier rubies.
    - rvm: 2.0.0
      gemfile: gemfiles/2.0.0-Gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/2.0.0-Gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/2.0.0-Gemfile
    - rvm: jruby-9.0.4.0
      gemfile: gemfiles/2.0.0-Gemfile
    # Upgrade to latest grape:
    - 2.2.6
      gemfile: gemfiles/2.2.0-Gemfile
    - 2.3.0
      gemfile: gemfiles/2.2.0-Gemfile
    - ruby-head
      gemfile: gemfiles/2.2.0-Gemfile
    - jruby-head
      gemfile: gemfiles/2.2.0-Gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  matrix:
    - RAILS=3.2.22
    - RAILS=4.1.13
    - RAILS=4.2.5.1
    - RAILS=5.0.1
    - RAILS=master
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"
  allow_failures:
    - RAILS=master

notifications:
  email: 
    recipients:
    - buermann@gmail.com
    on_success: change
    on_failure: always
